import{a as v,S as b,i}from"./assets/vendor-BNibzuFn.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const E="https://pixabay.com/api/",B="52755140-7ddce3cbb2c82e84a1ea5fb45",y=15;async function I(s,e=1){const r={key:B,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:y,page:e};try{return(await v.get(E,{params:r})).data}catch(a){throw a}}const h=document.getElementById("gallery"),p=document.getElementById("loader"),m=document.getElementById("load-more-btn"),g=new b(".gallery a",{captionsData:"alt",captionDelay:250});function A(s){if(!Array.isArray(s)||s.length===0)return;const e=s.map(r=>`
    <div class="photo-card">
      <a class="photo-link" href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      </a>
      <div class="info">
        <div class="stats">
          <span title="Likes">❤ ${r.likes}</span>
          <span title="Views">👁 ${r.views}</span>
          <span title="Comments">💬 ${r.comments}</span>
          <span title="Downloads">⬇ ${r.downloads}</span>
        </div>
      </div>
    </div>
  `).join("");h.insertAdjacentHTML("beforeend",e),g.refresh()}function S(){h.innerHTML="",g.refresh()}function P(){p.classList.remove("is-hidden")}function $(){p.classList.add("is-hidden")}function H(){m.classList.remove("is-hidden")}function c(){m.classList.add("is-hidden")}let l="",n=1,d=0,f=!1;const M=document.getElementById("search-form"),w=document.getElementById("search-input");c();M.addEventListener("submit",async s=>{s.preventDefault();const e=w.value.trim();if(!e){i.warning({title:"Warning",message:"Введите ключевое слово."});return}e!==l&&(l=e,n=1,d=0,S(),c()),await L({isNewSearch:e!==l})});m.addEventListener("click",async()=>{l&&await L()});async function L({isNewSearch:s=!1}={}){if(!f){f=!0,P(),c();try{s&&(n=1);const e=await I(l,n);d=e.totalHits??0;const r=Array.isArray(e.hits)?e.hits:[];if(r.length===0){i.info({title:"Info",message:"No images found. Try another query."}),c();return}A(r),n===1&&i.success({title:"Success",message:`Hooray! We found ${d} images.`}),n*y>=d?(c(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):H(),n+=1,n>2&&(await new Promise(t=>setTimeout(t,200)),O())}catch(e){console.error(e),i.error({title:"Error",message:(e==null?void 0:e.message)||"An error occurred while fetching images."})}finally{$(),f=!1}}}function O(){const s=h.querySelector(".photo-card");if(!s)return;const{height:e}=s.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}w.focus();
//# sourceMappingURL=index.js.map
